# Generated by Django 5.0.2 on 2024-04-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='faceb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Insta_url',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest',
            new_name='pinterest_url',
        ),
    ]
